export const VEDNOR_SIGN_UP_SUCCESS = 'VEDNOR_SIGN_UP_SUCCESS';
export const VEDNOR_SIGN_UP_FAIL = 'VEDNOR_SIGN_UP_FAIL';
export const VEDNOR_SIGN_UP_START = 'VEDNOR_SIGN_UP_START';

export const CUSTOMER_SIGN_UP_SUCCESS = 'CUSTOMER_SIGN_UP_SUCCESS';
export const CUSTOMER_SIGN_UP_FAIL = 'CUSTOMER_SIGN_UP_FAIL';
export const CUSTOMER_SIGN_UP_START = 'CUSTOMER_SIGN_UP_START';

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const SET_BAKER_SIGN_UP_REDIRECT_PATH = "SET_BAKER_SIGN_UP_REDIRECT_PATH";
export const SET_CUSTOMER_SIGN_UP_REDIRECT_PATH = "SET_CUSTOMER_SIGN_UP_REDIRECT_PATH"