//General
export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
//auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SIGN_UP_SUCCESS = 'VENDOR_SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'VENDOR_SIGN_UP_FAIL';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
//user
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA'; 
export const UPDATE_ROLE = "UPDATE_ROLE";
export const ADD_VENDOR = 'ADD_VENDOR';

export const GET_CHECKOUT_SESSION = "GET_CHECKOUT_SESSION";
export const INITIALIZE_CHECKOUT_SESSION = "INITIALIZE_CHECKOUT_SESSION";
export const CHECKOUT_CONFIRMED = "CHECKOUT_CONFIRMED";
export const CANCEL_CHECKOUT = "CANCEL_CHECKOUT";

//vendor
export const GET_VENDORS = "GET_VENDORS";
//food
export const ADD_MENU_ITEM = "ADD_MENU_ITEM";
export const SET_FOOD_ITEMS = "SET_FOOD_ITEMS";
export const CLEAR_FOOD_ITEMS = "CLEAR_FOOD_ITEMS";


