export const SHEF_SIGN_UP_SUCCESS = 'SHEF_SIGN_UP_SUCCESS';
export const SHEF_SIGN_UP_FAIL = 'SHEF_SIGN_UP_FAIL';
export const SHEF_SIGN_UP_START = 'SHEF_SIGN_UP_START';

export const CUSTOMER_SIGN_UP_SUCCESS = 'CUSTOMER_SIGN_UP_SUCCESS';
export const CUSTOMER_SIGN_UP_FAIL = 'CUSTOMER_SIGN_UP_FAIL';
export const CUSTOMER_SIGN_UP_START = 'CUSTOMER_SIGN_UP_START';